services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432

  api:
    image: node:18
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
